FROM sort/alpinego
LABEL maintainer "q@shellpub.com"

ARG app_name=simpledns

RUN set -x \
  && mkdir /${app_name} 

COPY ${app_name} /${app_name}/
RUN chmod +x /${app_name}/${app_name} 
WORKDIR /${app_name}

ENTRYPOINT ["./simpledns"]
